In [1]:
# opencv 라이브 카메라 테스트
import numpy as np
import cv2
import time

elapsed_time = 0                    # 전체 프레임 처리에 걸린 누적 시간(초)
title_name = 'opencv video test'    # 영상을 표시할 창 제목

def detectAndDisplay(image):
    # 한 프레임을 화면에 표시하고 처리 시간을 측정하는 함수
    start_time = time.time()        # 프레임 처리 시작 시각
    (h, w) = image.shape[:2]        # 프레임의 높이(h), 너비(w)

    cv2.imshow(title_name, image)   # 창에 현재 프레임 출력

    # 이미지 처리 확인
    end_time = time.time()          # 프레임 처리 종료 시각
    frame_time = end_time - start_time   # 이번 프레임 처리에 걸린 시간
    #print(start_time, end_time)
    global elapsed_time
    elapsed_time += frame_time      # 누적 처리 시간에 더함
    # print("Frame time {:.10f} seconds".format(frame_time))
    cv2.imshow(title_name, image)

# 비디오 사용, 0번 캠
vc = cv2.VideoCapture(0)            # 0번 카메라(기본 웹캠) 열기
time.sleep(5.0) # 5초 지연          # 카메라 초기화 대기
if not vc.isOpened:                 # 카메라가 열리지 않았으면 종료
    print('### Error opening video ###')
    exit(0)
vc.set(cv2.CAP_PROP_FRAME_WIDTH, 640)    # 캡처 해상도 너비 설정
vc.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)   # 캡처 해상도 높이 설정
while True:
    ret, frame = vc.read()         # 카메라에서 한 프레임 읽기 (ret: 성공 여부, frame: 이미지)
    print(ret, frame)
    # time.sleep(1.0) # 5초 지연
    if frame is None:              # 더 이상 읽을 프레임이 없으면 반복 종료
        print('### No more frame ###')
        vc.release()
        break
    detectAndDisplay(frame)        # 프레임을 화면에 표시

    if cv2.waitKey(1) & 0xFF == ord('q'):   # 'q' 키를 누르면 반복 종료
        break


# 메모리 정리
vc.release()                       # 카메라 자원 해제
cv2.destroyAllWindows()            # 모든 OpenCV 창 닫기

True [[[105  98 108]
  [107 101 109]
  [108 101 108]
  ...
  [144 144 146]
  [148 146 148]
  [151 148 150]]

 [[106  98 108]
  [107 100 108]
  [108 100 108]
  ...
  [144 143 145]
  [147 145 147]
  [149 146 148]]

 [[107  98 107]
  [107  98 108]
  [107  98 108]
  ...
  [144 142 144]
  [146 143 145]
  [147 144 146]]

 ...

 [[ 86  85  94]
  [ 91  89  98]
  [ 93  91  99]
  ...
  [ 32  28  30]
  [ 33  28  30]
  [ 38  32  36]]

 [[ 91  91  95]
  [ 94  93  97]
  [ 95  93  96]
  ...
  [ 30  28  30]
  [ 28  26  28]
  [ 31  29  32]]

 [[ 94  94  95]
  [ 95  94  95]
  [ 96  93  95]
  ...
  [ 28  28  31]
  [ 25  25  27]
  [ 28  28  30]]]
True [[[ 99  96 114]
  [102  99 116]
  [104 100 116]
  ...
  [142 145 144]
  [141 146 145]
  [141 146 145]]

 [[101  98 114]
  [103  99 115]
  [104  99 114]
  ...
  [144 146 146]
  [143 147 146]
  [143 147 146]]

 [[104  99 113]
  [104  98 112]
  [104  98 112]
  ...
  [147 147 147]
  [146 147 147]
  [146 147 147]]

 ...

 [[ 87  89  90]
  [ 87  89  90]
  [ 90  92